### ISSUE TITLE
Generate "ActiveDevice" aggregate metric based on presence of 'backgroundTask' event

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-server-staging-terraform#141]
https://github.com/cds-snc/covid-alert-server-staging-terraform/blob/7e9863f7a8ab8400224f94e2deccba5194fc7c05/server/aws/lambda/aggregate_values.js#L63

Looks like we'll need to generate an additional aggregate (or raw) metric as necessary to separate the # of background tasks per device type/appversion/province, from the number of unique devices per n.

Implementation is left as an exercise to the reader, but as it stands, we won't be able to determine the number of ios/android per dimension currently.

**Comment by obrien-j** [comment]
Note, we're both overthinking this. Any metric on a given date indicates a unique device and therefore, we just +1 every time we process a record (but in the event you've already split them, sure, just use the most likely to exist event id ) :)

**Comment by CalvinRodo** [comment]
I don't know I'm not sure I can guarantee that each device will only report metrics once a day, or that metrics for a specific date won't be spread over multiple days.

This is something I think I'll have to discuss with @craigzour

**Comment by craigzour** [comment]
@CalvinRodo We can definitely have a quick discussion about it but basically the application will only publish (internally) a background check event when we detect a new day. Before publishing the event it will aggregate the number of times we had background tasks fired so that we can provide a "count" value. When you get a background check event on the backend then the "count" represents the number of background tasks fired for the day that is right before the one represented by the timestamp of the event.

**Comment by CalvinRodo** [comment]
We are now sending an active-user metric.
