### ISSUE TITLE
Implement Traffic Shaping on Metric Aggregation 

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-server-staging-terraform#185]
This is probably something that needs to be handled on the App side of things instead of the server side. 

We could still add queues into the metric flow to manage reads and writes to the dynamodb tables but at the moment it's not worth it from a cost perspective. 

The bigger issue is the limit on the metrics endpoint we have a hard limit of 600 requests a second, at the moment we are hitting about 480 at peak, if we get close 550 requests a second we will need to push a release that adds back in some jitter.

**Comment by patheard** [comment]
We've confirmed with the app team that if the phone does not receive an HTTP 200 success when it posts to `/save-metrics`, it does not mark the metrics as published and will retry with an exponential backoff.

As a result of increased metric traffic, we are now seeing cases where the hard limit of requests is reached and Lambda throttling occurs, but there has not been a loss of metrics data because of retry/backoff logic in the app.
